services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PEADARS_WOODSHOP_BACKEND_DATABASE_PASSWORD}
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/peadars-woodshop-backend
    ports:
      - "3000:3000"
    depends_on:
      - db